// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/config/config.go

// Package configmock is a generated GoMock package.
package configmock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// GetPactBrokerToken mocks base method.
func (m *MockConfig) GetPactBrokerToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPactBrokerToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPactBrokerToken indicates an expected call of GetPactBrokerToken.
func (mr *MockConfigMockRecorder) GetPactBrokerToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPactBrokerToken", reflect.TypeOf((*MockConfig)(nil).GetPactBrokerToken))
}

// GetPactBrokerURl mocks base method.
func (m *MockConfig) GetPactBrokerURl() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPactBrokerURl")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPactBrokerURl indicates an expected call of GetPactBrokerURl.
func (mr *MockConfigMockRecorder) GetPactBrokerURl() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPactBrokerURl", reflect.TypeOf((*MockConfig)(nil).GetPactBrokerURl))
}

// GetServerPort mocks base method.
func (m *MockConfig) GetServerPort() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerPort")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServerPort indicates an expected call of GetServerPort.
func (mr *MockConfigMockRecorder) GetServerPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerPort", reflect.TypeOf((*MockConfig)(nil).GetServerPort))
}
