name: "go-cache"
description: "go installing with cache"
runs:
  using: composite
  steps:
    - name: Set up Go with cache
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version: 1.19

    - name: Go version
      shell: bash
      run: go version